### ISSUE TITLE
Upload Indicators API - script.py

### ISSUE THREAD

**Issue by PiusO** [cudeso/misp2sentinel#27]
When i run python3 script.py, I get the following, that part of the script differs to the original, any idea what's going on?

script.py:1: DeprecationWarning: 
As our baseline system is the latest Ubuntu LTS, and Ubuntu LTS 22.04 has Python 3.10 available,
we will officially deprecate python versions below 3.10 on January 1st 2024.
**Please update your codebase.**
  from pymisp import PyMISP
Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.172 - Python 3.8', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Cookie': 'CAKEPHP=k3g4cs883cdpmkdr8ounmdf3sb64ntt8', 'Content-Length': '381', 'content-type': 'application/json'}
Request body:
{"returnFormat": "stix2", "page": 2, "limit": 50, "tags": ["workflow:state=\"complete\""], "withAttachments": 0, "metadata": 0, "published": 1, "enforceWarninglist": 0, "to_ids": 1, "includeEventUuid": 0, "includeEventTags": 0, "sgReferenceOnly": 0, "includeContext": 0, "headerless": 0, "includeSightings": 0, "includeDecayScore": 0, "includeCorrelations": 0, "excludeDecayed": 0}
Response (if any):
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/restSearch"}
Traceback (most recent call last):
  File "script.py", line 269, in <module>
    main()
  File "script.py", line 252, in main
    with RequestManager(total_indicators, logger) as request_manager:
TypeError: __init__() takes 2 positional arguments but 3 were given

**Comment by PiusO** [comment]
Resolved
